import React from 'react'

export const styles: Record<string, React.CSSProperties> = {
  blockName: {
    fontSize: '0.85rem',
    fontWeight: 700,
    color: '#cdd6f4',
    fontFamily: 'monospace',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  panel: {
    position: 'fixed',
    top: 0,
    right: 0,
    height: '100vh',
    background: '#1e1e2e',
    borderLeft: '1px solid #313244',
    display: 'flex',
    flexDirection: 'column',
    zIndex: 100,
  },
  resizeHandle: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    cursor: 'col-resize',
    zIndex: 10,
    background: 'transparent',
    transition: 'background 0.15s',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.6rem 0.8rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
  },
  fileName: {
    fontSize: '0.78rem',
    color: '#cdd6f4',
    fontFamily: 'monospace',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: 340,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    color: '#6c7086',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '0 4px',
  },
  undoRedoBtn: {
    background: 'none',
    border: '1px solid #313244',
    borderRadius: 4,
    color: '#6c7086',
    cursor: 'pointer',
    fontSize: '1rem',
    padding: '1px 6px',
    lineHeight: 1,
    transition: 'color 0.1s, border-color 0.1s',
  },
  tabs: {
    display: 'flex',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
  },
  tab: {
    flex: 1,
    padding: '0.45rem',
    background: 'none',
    border: 'none',
    color: '#6c7086',
    cursor: 'pointer',
    fontSize: '0.82rem',
    fontWeight: 500,
    transition: 'color 0.15s',
  },
  activeTab: {
    color: '#cdd6f4',
    borderBottom: '2px solid #89b4fa',
  },
  content: {
    flex: 1,
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  },
  loading: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    color: '#6c7086',
    fontSize: '0.85rem',
  },
  placeholder: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 8,
    color: '#cdd6f4',
    fontSize: '0.9rem',
  },
  bindingsPanel: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    overflow: 'hidden',
  },
  bindingsEmpty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    gap: 8,
    color: '#6c7086',
    fontSize: '0.82rem',
    textAlign: 'center' as const,
    padding: '2rem',
  },
  bindingsNodeHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 0.8rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
  },
  bindingsNodeTag: {
    fontFamily: 'monospace',
    color: '#89b4fa',
    fontWeight: 700,
    fontSize: '0.88rem',
  },
  bindingsNodeOwner: {
    fontSize: '0.75rem',
    color: '#6c7086',
  },
  bindingsScroll: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '0.4rem 0',
  },
  multiComponentBanner: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    padding: '0.45rem 0.75rem',
    background: 'rgba(249,226,175,0.08)',
    borderBottom: '1px solid rgba(249,226,175,0.22)',
    flexShrink: 0,
  },
  multiComponentBannerIcon: {
    color: '#f9e2af',
    fontSize: '0.8rem',
    flexShrink: 0,
    marginTop: 1,
  },
  multiComponentBannerText: {
    color: '#a6adc8',
    fontSize: '0.73rem',
    lineHeight: 1.45,
  },
  noPropTypeBanner: {
    margin: '0.5rem 0.75rem',
    padding: '0.6rem 0.75rem',
    background: 'rgba(249,226,175,0.06)',
    border: '1px solid rgba(249,226,175,0.2)',
    borderRadius: 6,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 8,
  },
  noPropTypeBannerText: {
    fontSize: '0.75rem',
    lineHeight: 1.5,
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '2px 4px',
  },
  noPropTypeCta: {
    alignSelf: 'flex-start' as const,
    background: '#313244',
    border: '1px solid rgba(249,226,175,0.3)',
    borderRadius: 5,
    color: '#f9e2af',
    cursor: 'pointer',
    fontSize: '0.72rem',
    padding: '4px 10px',
    fontWeight: 600,
  },
  bindingsEmptyAttrs: {
    color: '#6c7086',
    fontSize: '0.78rem',
    padding: '0.8rem 1rem',
  },
  componentEmptyState: {
    padding: '0.8rem 1rem',
    lineHeight: 1.6,
  },
  attrRowWrap: {
    borderBottom: '1px solid #232336',
  },
  attrRow: {
    display: 'grid',
    alignItems: 'center',
    gap: 8,
    padding: '0.35rem 0.8rem',
  },
  attrRowHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '0.35rem 0.8rem',
    cursor: 'pointer',
    userSelect: 'none' as const,
  },
  rowChevron: {
    fontSize: '0.55rem',
    color: '#585b70',
    width: 10,
    flexShrink: 0,
  },
  attrName: {
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '0.78rem',
    color: '#89b4fa',
    fontWeight: 600,
  },
  attrValueCell: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    minWidth: 0,
  },
  attrInput: {
    background: '#1e1e2e',
    border: '1px solid #45475a',
    borderRadius: 4,
    color: '#cdd6f4',
    padding: '3px 6px',
    fontSize: '0.75rem',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    outline: 'none',
    minWidth: 0,
  },
  attrReadonly: {
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '0.75rem',
    color: '#a6adc8',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  attrRowDom: {
    display: 'grid',
    gridTemplateColumns: '100px 1fr',
    alignItems: 'center',
    gap: 8,
    padding: '0.35rem 0.8rem',
    borderBottom: '1px solid #232336',
  },
  attrRowBody: {
    padding: '0 0.8rem 0.5rem 1.6rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
  },
  attrBodyRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  attrBodyLabel: {
    fontSize: '0.62rem',
    color: '#6c7086',
    minWidth: 34,
    textTransform: 'uppercase' as const,
    fontWeight: 700,
    letterSpacing: '0.06em',
  },
  modeToggle: {
    display: 'flex',
    gap: 0,
    borderRadius: 4,
    overflow: 'hidden',
    border: '1px solid #45475a',
    flexShrink: 0,
  },
  modeBtn: {
    background: 'none',
    border: 'none',
    color: '#585b70',
    cursor: 'pointer',
    fontSize: '0.6rem',
    padding: '2px 5px',
    fontWeight: 600,
    letterSpacing: '0.03em',
  },
  modeBtnActive: {
    background: '#313244',
    color: '#cdd6f4',
  },
  badgeOwner: {
    fontSize: '0.58rem',
    color: '#6c7086',
    border: '1px solid #45475a',
    borderRadius: 10,
    padding: '1px 5px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    flexShrink: 0,
  },
  badgeElement: {
    fontSize: '0.58rem',
    color: '#45475a',
    border: '1px solid #313244',
    borderRadius: 10,
    padding: '1px 5px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    flexShrink: 0,
  },
  deleteBtn: {
    background: 'none',
    border: 'none',
    color: '#f38ba8',
    cursor: 'pointer',
    fontSize: '0.7rem',
    padding: '0 2px',
    fontWeight: 700,
    lineHeight: 1,
    flexShrink: 0,
    opacity: 0.7,
  },
  saveBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
    padding: '0.5rem 0.8rem',
    background: '#181825',
    borderTop: '1px solid #313244',
    flexShrink: 0,
  },
  saveBtn: {
    background: '#89b4fa',
    color: '#1e1e2e',
    border: 'none',
    borderRadius: 4,
    padding: '0.35rem 1rem',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: '0.78rem',
  },
  cancelBtn: {
    background: 'none',
    border: '1px solid #45475a',
    borderRadius: 4,
    color: '#6c7086',
    padding: '0.3rem 0.8rem',
    cursor: 'pointer',
    fontSize: '0.75rem',
  },
  confirmBtn: {
    background: '#89b4fa',
    border: 'none',
    borderRadius: 4,
    color: '#1e1e2e',
    padding: '0.3rem 0.8rem',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 600,
  },
  savedMsg: {
    color: '#a6e3a1',
    fontSize: '0.78rem',
  },
  errorMsg: {
    color: '#f38ba8',
    fontSize: '0.78rem',
  },
  diffHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '0.35rem 0.8rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
  },
  diffFileTab: {
    background: 'none',
    border: '1px solid #45475a',
    borderRadius: 4,
    color: '#cdd6f4',
    padding: '2px 8px',
    fontSize: '0.72rem',
    cursor: 'pointer',
    fontFamily: 'monospace',
  },
  diffFileTabActive: {
    background: '#313244',
    borderColor: '#89b4fa',
    color: '#89b4fa',
  },
  diffLabel: {
    fontSize: '0.75rem',
    color: '#a6adc8',
    fontWeight: 500,
  },
  changeSummary: {
    padding: '0.5rem 0.8rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
  },
  changeSummaryTitle: {
    fontSize: '0.78rem',
    fontWeight: 600,
    color: '#cdd6f4',
    marginBottom: 4,
  },
  changeSummaryItem: {
    fontSize: '0.72rem',
    color: '#a6adc8',
    padding: '1px 0',
    fontFamily: 'system-ui, sans-serif',
  },
  accordionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '0.4rem 0.8rem',
    background: '#1e1e2e',
    borderBottom: '1px solid #313244',
    cursor: 'pointer',
    userSelect: 'none' as const,
  },
  accordionHeaderActive: {
    background: '#181825',
  },
  accordionChevron: {
    fontSize: '0.65rem',
    color: '#6c7086',
    width: 12,
    flexShrink: 0,
  },
  accordionFileName: {
    fontSize: '0.72rem',
    fontFamily: 'monospace',
    color: '#89b4fa',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  accordionBadge: {
    fontSize: '0.65rem',
    color: '#a6e3a1',
    background: '#1e1e2e',
    border: '1px solid #313244',
    borderRadius: 8,
    padding: '0 5px',
    flexShrink: 0,
  },
  addAttrBtn: {
    background: 'none',
    border: '1px dashed #45475a',
    borderRadius: 4,
    color: '#6c7086',
    cursor: 'pointer',
    fontSize: '0.75rem',
    padding: '0.4rem 0.8rem',
    margin: '0.4rem 0.8rem',
    textAlign: 'left' as const,
  },
  addPropForm: {
    padding: '0.5rem 0.8rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 6,
    borderTop: '1px solid #232336',
  },
  addPropRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  addPropActions: {
    display: 'flex',
    gap: 6,
    justifyContent: 'flex-end',
  },
  inferBtn: {
    background: 'none',
    border: '1px solid #45475a',
    borderRadius: 4,
    color: '#6c7086',
    cursor: 'pointer',
    fontSize: '0.72rem',
    padding: '2px 5px',
    lineHeight: 1,
  },
}

export const scopeStyles: Record<string, React.CSSProperties> = {
  panel: {
    flexShrink: 0,
    borderBottom: '1px solid #1e1e2e',
    maxHeight: 280,
    display: 'flex',
    flexDirection: 'column',
    background: '#13131f',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    width: '100%',
    background: 'none',
    borderTop: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    borderBottom: '1px solid #1e1e2e',
    color: '#7f849c',
    cursor: 'pointer',
    padding: '0.4rem 0.9rem',
    fontSize: '0.68rem',
    fontWeight: 700,
    textAlign: 'left' as const,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    flexShrink: 0,
  },
  chevron: { fontSize: '0.6rem', color: '#585b70', marginRight: 1 },
  usedBadge: {
    marginLeft: 'auto',
    fontSize: '0.67rem',
    color: '#a6e3a1',
    fontWeight: 600,
    background: 'rgba(166,227,161,0.1)',
    border: '1px solid rgba(166,227,161,0.25)',
    borderRadius: 10,
    padding: '1px 7px',
  },
  body: { overflowY: 'auto' as const, padding: '0.4rem 0 0.6rem' },
  layer: { marginBottom: 6 },
  layerHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    marginBottom: 4,
    paddingRight: 10,
  },
  layerNameCurrent: {
    fontSize: '0.75rem',
    fontWeight: 700,
    color: '#89b4fa',
    letterSpacing: '0.01em',
  },
  layerNameParent: {
    fontSize: '0.72rem',
    color: '#6c7086',
    letterSpacing: '0.01em',
  },
  currentBadge: {
    marginLeft: 'auto',
    fontSize: '0.6rem',
    color: '#1e1e2e',
    background: '#89b4fa',
    borderRadius: 10,
    padding: '1px 7px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  parentBadge: {
    marginLeft: 'auto',
    fontSize: '0.6rem',
    color: '#6c7086',
    background: 'transparent',
    border: '1px solid #45475a',
    borderRadius: 10,
    padding: '1px 7px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  group: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 5,
    marginBottom: 3,
    paddingLeft: 14,
  },
  groupLabel: {
    fontSize: '0.58rem',
    color: '#45475a',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.07em',
    minWidth: 30,
    paddingTop: 3,
    flexShrink: 0,
  },
  items: { display: 'flex', flexWrap: 'wrap' as const, gap: '3px 4px' },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    fontSize: '0.71rem',
    color: '#45475a',
    padding: '2px 7px',
    borderRadius: 99,
    background: 'transparent',
    border: '1px solid #2a2a3d',
  },
  itemUsed: {
    color: '#b4cefa',
    background: 'rgba(137,180,250,0.1)',
    border: '1px solid rgba(137,180,250,0.28)',
  },
  itemDot: { fontSize: '0.5rem' },
  itemName: {
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '0.7rem',
    fontWeight: 500,
  },
  itemType: {
    fontSize: '0.62rem',
    color: '#45475a',
    fontStyle: 'italic' as const,
    marginLeft: 1,
  },
  addChipBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 20,
    height: 20,
    borderRadius: '50%',
    border: '1px dashed #45475a',
    background: 'transparent',
    color: '#6c7086',
    fontSize: 13,
    fontWeight: 700,
    cursor: 'pointer',
    lineHeight: 1,
    padding: 0,
    flexShrink: 0,
  },
  removeBtn: {
    marginLeft: 2,
    fontSize: 9,
    color: '#f38ba8',
    cursor: 'pointer',
    lineHeight: 1,
    fontWeight: 700,
  } as React.CSSProperties,
  confirmOverlay: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
    marginLeft: 4,
    fontSize: 9,
    color: '#f38ba8',
    fontFamily: 'system-ui, sans-serif',
  } as React.CSSProperties,
  confirmYes: {
    cursor: 'pointer',
    fontWeight: 700,
    padding: '1px 4px',
    borderRadius: 3,
    border: '1px solid #f38ba8',
    lineHeight: 1.4,
    fontSize: 9,
    color: '#f38ba8',
  } as React.CSSProperties,
  confirmNo: {
    cursor: 'pointer',
    padding: '1px 4px',
    borderRadius: 3,
    border: '1px solid #45475a',
    lineHeight: 1.4,
    fontSize: 9,
    color: '#6c7086',
  } as React.CSSProperties,
}
