import React from 'react'

export const styles: Record<string, React.CSSProperties> = {
  panel: {
    width: 260,
    minWidth: 260,
    flexShrink: 0,
    background: '#1e1e2e',
    borderRight: '1px solid #313244',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  nodeCount: {
    color: '#6c7086',
    fontWeight: 400,
    textTransform: 'none',
    letterSpacing: 0,
    fontSize: 10,
  },
  sectionHeader: {
    padding: '0.5rem 0.75rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    color: '#6c7086',
    fontWeight: 600,
    fontSize: 10,
    flexShrink: 0,
    fontFamily: 'system-ui, sans-serif',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.07em',
  },
  pageSectionDivider: {
    height: 1,
    background: '#313244',
    flexShrink: 0,
  },
  pagesSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    maxHeight: '50vh',
    flexShrink: 0,
    borderBottom: '1px solid #313244',
  },
  pagesScroll: {
    overflowY: 'auto' as const,
    flex: 1,
  },
  addPageOuter: {
    padding: '0.45rem 0.6rem',
    background: '#181825',
    borderTop: '1px solid #313244',
    flexShrink: 0,
  },
  addPageBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '0.3rem 0.5rem',
    cursor: 'pointer',
    color: '#a6e3a1',
    fontSize: 11,
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 500,
    background: 'transparent',
    border: '1px solid #45475a',
    borderRadius: 6,
    userSelect: 'none' as const,
    transition: 'background 0.12s, border-color 0.12s',
  },
  pageSearch: {
    padding: '0.45rem 0.6rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
  },
  pageSearchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '0.3rem 0.5rem',
    background: '#1e1e2e',
    border: '1px solid #45475a',
    borderRadius: 6,
  },
  pageSearchIcon: {
    color: '#6c7086',
    fontSize: 13,
    flexShrink: 0,
    userSelect: 'none' as const,
    lineHeight: 1,
  },
  pageSearchInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    outline: 'none',
    color: '#cdd6f4',
    fontSize: 11,
    fontFamily: 'system-ui, sans-serif',
    padding: 0,
  },
  scroll: {
    overflowY: 'auto',
    flex: 1,
    paddingBottom: 8,
  },
  empty: {
    color: '#6c7086',
    fontSize: 11,
    padding: '1rem',
    fontFamily: 'system-ui, sans-serif',
  },
}
