import React from 'react'

export const modalStyles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed', inset: 0, zIndex: 1000,
    background: 'rgba(0,0,0,0.55)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  dialog: {
    background: '#1e1e2e',
    border: '1px solid #313244',
    borderRadius: 10,
    width: 360,
    boxShadow: '0 8px 40px rgba(0,0,0,0.5)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '0.75rem 1rem',
    borderBottom: '1px solid #313244',
    background: '#181825',
  },
  title: { color: '#cdd6f4', fontWeight: 600, fontSize: 13, fontFamily: 'system-ui, sans-serif' },
  closeBtn: {
    background: 'none', border: 'none', color: '#6c7086', fontSize: 18,
    cursor: 'pointer', lineHeight: 1, padding: '0 2px',
  },
  body: { padding: '1rem', display: 'flex', flexDirection: 'column', gap: 10 },
  label: { color: '#9ca3af', fontSize: 11, fontFamily: 'system-ui, sans-serif' },
  input: {
    background: '#181825', border: '1px solid #45475a', borderRadius: 6,
    color: '#cdd6f4', fontSize: 13, fontFamily: 'system-ui, sans-serif',
    padding: '0.45rem 0.6rem', outline: 'none',
  },
  preview: {
    display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '4px 10px',
    background: '#181825', border: '1px solid #313244', borderRadius: 6,
    padding: '0.5rem 0.6rem',
  },
  previewKey: { color: '#6c7086', fontSize: 11, fontFamily: 'system-ui, sans-serif' },
  previewVal: { color: '#a6e3a1', fontSize: 11, fontFamily: 'monospace' },
  error: {
    background: '#3b1f2e', border: '1px solid #f38ba8', borderRadius: 6,
    color: '#f38ba8', fontSize: 11, fontFamily: 'system-ui, sans-serif',
    padding: '0.4rem 0.6rem',
  },
  actions: { display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 4 },
  cancelBtn: {
    background: 'transparent', border: '1px solid #45475a', borderRadius: 6,
    color: '#9ca3af', fontSize: 12, fontFamily: 'system-ui, sans-serif',
    padding: '0.35rem 0.9rem', cursor: 'pointer',
  },
  submitBtn: {
    background: '#a6e3a1', border: 'none', borderRadius: 6,
    color: '#1e1e2e', fontSize: 12, fontFamily: 'system-ui, sans-serif',
    fontWeight: 700, padding: '0.35rem 0.9rem', cursor: 'pointer',
  },
}

export const appStyles: Record<string, React.CSSProperties> = {
  root: { display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden' },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0 1.2rem',
    height: 44,
    background: '#11111b',
    borderBottom: '1px solid #1e1e2e',
    flexShrink: 0,
  },
  logo: {
    fontWeight: 700,
    fontSize: '0.9rem',
    color: '#cdd6f4',
    letterSpacing: 1,
    textTransform: 'uppercase' as const,
    opacity: 0.9,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  hint: { fontSize: '0.72rem', color: '#45475a', marginLeft: 'auto', letterSpacing: 0.2 },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '0.3rem 1.2rem',
    background: '#181825',
    borderBottom: '1px solid #313244',
    flexShrink: 0,
    fontFamily: 'system-ui, sans-serif',
    fontSize: '0.72rem',
  },
  breadcrumbItem: {
    color: '#6c7086',
    cursor: 'default',
  },
  breadcrumbSep: {
    color: '#45475a',
    fontSize: '0.8rem',
  },
  breadcrumbCurrent: {
    color: '#cba6f7',
    fontWeight: 600,
    fontFamily: 'monospace',
  },
  tabs: {
    display: 'flex',
    gap: 2,
  },
  tab: {
    background: 'transparent',
    border: 'none',
    borderBottom: '2px solid transparent',
    borderRadius: 0,
    color: '#585b70',
    fontSize: '0.75rem',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 500,
    padding: '0 0.9rem',
    height: 44,
    cursor: 'pointer',
    transition: 'color 0.15s, border-color 0.15s',
    letterSpacing: 0.2,
  },
  tabActive: {
    borderBottomColor: '#89b4fa',
    color: '#cdd6f4',
    fontWeight: 600,
  },
  emptyState: {
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    height: '100%', color: '#9ca3af', fontSize: '0.85rem',
    fontFamily: 'system-ui, sans-serif',
  },
  main: { flex: 1, display: 'flex', overflow: 'hidden', position: 'relative' },
  canvasColumn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    transition: 'margin-right 0.2s ease',
  },
  canvas: {
    flex: 1,
    overflow: 'auto',
    background: '#f5f5f5',
  },
}
